stages:
  - analyse
  - archive

variables:
  COMMIT_ID: "$CI_COMMIT_SHORT_SHA"

analyse-job:
  stage: analyse
  script:
    - for script in analyse/*.py; do
        echo "Executing $script";
        python3 $script;
      done
  artifacts:
    paths:
      - charts/
    expire_in: 1 week

archive-results:
  stage: archive
  script:
    - mkdir -p /var/www/$COMMIT_ID
    - cp -r charts/* /var/www/$COMMIT_ID/
    - echo "Results archived in /var/www/$COMMIT_ID"

    - echo "<html><body><h1>Archived Commits</h1>" > "/var/www/index.html"
    - echo "<table border=\"1\" cellpadding=\"6\" cellspacing=\"0\">" >> "/var/www/index.html"
    - echo "<tr><th>Commit ID</th><th>Date</th></tr>" >> "/var/www/index.html"

    # Add each directory as a row, sorted by mtime (most recent first)
    - |
      find "/var/www" -mindepth 1 -maxdepth 1 -type d -printf "%T@ %f\n" \
      | sort -nr \
      | while read timestamp commit; do
          # Skip the "www" folder if it's present as part of the path
          [ "$commit" = "www" ] && continue
          date_str=$(date -d @"${timestamp%.*}" +"%Y-%m-%d %H:%M:%S")
          echo "<tr><td><a href=\"./$commit/\">$commit</a></td><td>$date_str</td></tr>" >> "/var/www/index.html"
        done

    - echo "</table></body></html>" >> "/var/www/index.html"
  dependencies:
    - analyse-job
